import './globals.css'
import { Inter } from 'next/font/google'
import Providers from "@/app/providers";
import {ReactQueryDevtools} from "@tanstack/react-query-devtools";
import HeadNavBar from "@/components/HeadNavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <Providers>
        <ReactQueryDevtools />
        <body className="mx-12 lg:mx-96 bg-black-100 text-white">
          <HeadNavBar />
          {children}
          <Footer />
        </body>
      </Providers>
      </html>
  )
}
